# Generated by Django 4.2.11 on 2026-06-19 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoadSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='路段名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='路段编号')),
                ('start_location', models.CharField(max_length=200, verbose_name='起点位置')),
                ('end_location', models.CharField(max_length=200, verbose_name='终点位置')),
                ('length_km', models.FloatField(default=0, verbose_name='长度(公里)')),
                ('historical_info', models.TextField(blank=True, verbose_name='历史背景')),
                ('status', models.CharField(choices=[('good', '状态良好'), ('warning', '需要关注'), ('critical', '亟待维护')], default='good', max_length=20, verbose_name='路段状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '路段档案',
                'verbose_name_plural': '路段档案',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='点位编号')),
                ('name', models.CharField(max_length=200, verbose_name='点位名称')),
                ('point_type', models.CharField(choices=[('stone_step', '石阶'), ('road_stele', '路碑'), ('drainage', '排水沟')], max_length=20, verbose_name='点位类型')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('description', models.TextField(blank=True, verbose_name='点位描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('road_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='roads.roadsection', verbose_name='所属路段')),
            ],
            options={
                'verbose_name': '点位',
                'verbose_name_plural': '点位',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='InspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(verbose_name='巡查日期')),
                ('inspector', models.CharField(max_length=100, verbose_name='巡查人员')),
                ('wear_level', models.IntegerField(choices=[(1, '轻微'), (2, '一般'), (3, '较重'), (4, '严重')], verbose_name='磨损等级')),
                ('wear_description', models.TextField(blank=True, verbose_name='磨损描述')),
                ('maintenance_suggestion', models.TextField(blank=True, verbose_name='维护建议')),
                ('handled', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('handled_date', models.DateField(blank=True, null=True, verbose_name='处理日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='roads.point', verbose_name='点位')),
            ],
            options={
                'verbose_name': '巡查记录',
                'verbose_name_plural': '巡查记录',
                'ordering': ['-inspection_date'],
                'unique_together': {('point', 'inspection_date')},
            },
        ),
    ]
