# Generated by Django 4.2.11 on 2026-06-19 16:27

from django.db import migrations, models
import django.db.models.deletion
import roads.models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='工单标题')),
                ('description', models.TextField(blank=True, verbose_name='工单描述')),
                ('status', models.CharField(choices=[('pending', '待派发'), ('dispatched', '已派发'), ('rectifying', '整改中'), ('pending_review', '待复核'), ('closed', '已闭环'), ('rejected', '复核不通过')], default='pending', max_length=20, verbose_name='工单状态')),
                ('priority', models.CharField(choices=[('urgent', '紧急'), ('high', '高'), ('medium', '中'), ('low', '低')], default='high', max_length=10, verbose_name='优先级')),
                ('assigned_to', models.CharField(blank=True, max_length=100, verbose_name='指派人员')),
                ('dispatch_note', models.TextField(blank=True, verbose_name='派发说明')),
                ('rectification_result', models.TextField(blank=True, verbose_name='整改结果')),
                ('review_note', models.TextField(blank=True, verbose_name='复核意见')),
                ('reviewer', models.CharField(blank=True, max_length=100, verbose_name='复核人')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='整改期限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('dispatched_at', models.DateTimeField(blank=True, null=True, verbose_name='派发时间')),
                ('rectified_at', models.DateTimeField(blank=True, null=True, verbose_name='整改完成时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='复核时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='闭环时间')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_orders', to='roads.inspectionrecord', verbose_name='关联巡查记录')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_orders', to='roads.point', verbose_name='点位')),
            ],
            options={
                'verbose_name': '任务工单',
                'verbose_name_plural': '任务工单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=roads.models.photo_upload_path, verbose_name='照片')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='照片说明')),
                ('photo_type', models.CharField(choices=[('inspection', '巡查照片'), ('damage', '破损照片'), ('rectification', '整改照片'), ('verification', '复核照片')], default='inspection', max_length=20, verbose_name='照片类型')),
                ('taken_at', models.DateField(blank=True, null=True, verbose_name='拍摄日期')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='roads.inspectionrecord', verbose_name='巡查记录')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='roads.point', verbose_name='点位')),
            ],
            options={
                'verbose_name': '照片档案',
                'verbose_name_plural': '照片档案',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('wear_critical', '严重磨损预警'), ('wear_worsening', '磨损恶化趋势'), ('task_overdue', '工单超期预警'), ('unhandled_long', '长期未处理预警')], max_length=20, verbose_name='预警类型')),
                ('alert_level', models.CharField(choices=[('info', '提示'), ('warning', '警告'), ('critical', '紧急')], max_length=20, verbose_name='预警等级')),
                ('message', models.TextField(verbose_name='预警信息')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='roads.point', verbose_name='点位')),
                ('related_inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roads.inspectionrecord', verbose_name='关联巡查记录')),
            ],
            options={
                'verbose_name': '风险预警',
                'verbose_name_plural': '风险预警',
                'ordering': ['-created_at'],
            },
        ),
    ]
