# Generated by Django 4.2.11 on 2026-06-19 17:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0002_taskorder_photo_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hazard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='隐患编号')),
                ('title', models.CharField(max_length=200, verbose_name='隐患标题')),
                ('location_type', models.CharField(choices=[('stone_step', '石阶'), ('slope', '边坡'), ('drainage', '排水沟'), ('bridge_culvert', '桥涵'), ('retaining_wall', '挡墙'), ('tunnel', '隧道/涵洞'), ('road_surface', '路面'), ('other', '其他')], max_length=30, verbose_name='位置类型')),
                ('hazard_type', models.CharField(choices=[('landslide', '塌方/滑坡'), ('waterlogging', '积水'), ('rockfall', '落石'), ('fracture', '断裂/开裂'), ('slippery', '湿滑'), ('subsidence', '沉降/塌陷'), ('blockage', '堵塞'), ('erosion', '冲刷/侵蚀'), ('deformation', '变形'), ('other', '其他')], max_length=30, verbose_name='隐患类型')),
                ('hazard_level', models.CharField(choices=[('safe', '安全'), ('info', '提示'), ('warning', '警告'), ('severe', '严重'), ('critical', '紧急')], default='info', max_length=20, verbose_name='预警等级')),
                ('status', models.CharField(choices=[('reported', '已上报'), ('assessing', '评估中'), ('pending_disposal', '待处置'), ('disposing', '处置中'), ('monitoring', '监控观察'), ('resolved', '已消除'), ('closed', '已闭环')], default='reported', max_length=30, verbose_name='处置状态')),
                ('description', models.TextField(blank=True, verbose_name='隐患描述')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='纬度')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('location_desc', models.CharField(blank=True, max_length=300, verbose_name='具体位置描述')),
                ('reported_by', models.CharField(max_length=100, verbose_name='上报人')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='上报时间')),
                ('reported_date', models.DateField(blank=True, null=True, verbose_name='上报日期')),
                ('control_suggestion', models.CharField(choices=[('none', '无需封控'), ('caution', '设置警示标识'), ('speed_limit', '限速通行'), ('single_lane', '单向/间歇通行'), ('detour', '建议绕行'), ('full_closure', '全路段封闭')], default='none', max_length=30, verbose_name='封控建议')),
                ('passage_status', models.CharField(choices=[('normal', '正常通行'), ('caution', '谨慎通行'), ('restricted', '限制通行'), ('detour', '建议绕行'), ('closed', '禁止通行')], default='normal', max_length=30, verbose_name='通行状态')),
                ('assess_note', models.TextField(blank=True, verbose_name='评估意见')),
                ('assessed_by', models.CharField(blank=True, max_length=100, verbose_name='评估人')),
                ('assessed_at', models.DateTimeField(blank=True, null=True, verbose_name='评估时间')),
                ('disposal_deadline', models.DateField(blank=True, null=True, verbose_name='处置期限')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='消除时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='闭环时间')),
                ('closed_by', models.CharField(blank=True, max_length=100, verbose_name='闭环人')),
                ('affected_length_m', models.FloatField(blank=True, default=0, verbose_name='影响长度(米)')),
                ('casualty_info', models.TextField(blank=True, verbose_name='人员伤亡情况')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('inspection_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hazards', to='roads.inspectionrecord', verbose_name='来源巡查记录')),
                ('point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hazards', to='roads.point', verbose_name='关联点位')),
                ('road_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hazards', to='roads.roadsection', verbose_name='所属路段')),
            ],
            options={
                'verbose_name': '灾害隐患',
                'verbose_name_plural': '灾害隐患',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='RoadPassageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passage_status', models.CharField(choices=[('normal', '正常通行'), ('caution', '谨慎通行'), ('restricted', '限制通行'), ('detour', '建议绕行'), ('closed', '禁止通行')], default='normal', max_length=30, verbose_name='当前通行状态')),
                ('active_hazard_count', models.IntegerField(default=0, verbose_name='活跃隐患数')),
                ('critical_hazard_count', models.IntegerField(default=0, verbose_name='紧急隐患数')),
                ('affected_start_km', models.FloatField(blank=True, null=True, verbose_name='影响起点公里')),
                ('affected_end_km', models.FloatField(blank=True, null=True, verbose_name='影响终点公里')),
                ('status_reason', models.CharField(blank=True, max_length=500, verbose_name='状态原因')),
                ('updated_by', models.CharField(blank=True, max_length=100, verbose_name='更新人')),
                ('effective_from', models.DateTimeField(auto_now_add=True, verbose_name='生效时间')),
                ('estimated_resume', models.DateTimeField(blank=True, null=True, verbose_name='预计恢复时间')),
                ('notice_public', models.TextField(blank=True, verbose_name='对外公告内容')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('road_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passage_statuses', to='roads.roadsection', unique=True, verbose_name='所属路段')),
            ],
            options={
                'verbose_name': '路段通行状态',
                'verbose_name_plural': '路段通行状态',
                'ordering': ['road_section__code'],
            },
        ),
        migrations.CreateModel(
            name='HazardDisposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposal_type', models.CharField(choices=[('reported', '隐患上报'), ('assessed', '等级评估'), ('dispatched', '派发任务'), ('onsite', '现场处置'), ('reinforced', '加固维修'), ('cleaned', '清理疏通'), ('monitored', '设置监控'), ('controlled', '封控警戒'), ('inspected', '复核验收'), ('closed', '闭环归档'), ('other', '其他操作')], max_length=30, verbose_name='处置类型')),
                ('status_before', models.CharField(blank=True, choices=[('reported', '已上报'), ('assessing', '评估中'), ('pending_disposal', '待处置'), ('disposing', '处置中'), ('monitoring', '监控观察'), ('resolved', '已消除'), ('closed', '已闭环')], max_length=30, verbose_name='操作前状态')),
                ('status_after', models.CharField(blank=True, choices=[('reported', '已上报'), ('assessing', '评估中'), ('pending_disposal', '待处置'), ('disposing', '处置中'), ('monitoring', '监控观察'), ('resolved', '已消除'), ('closed', '已闭环')], max_length=30, verbose_name='操作后状态')),
                ('level_before', models.CharField(blank=True, choices=[('safe', '安全'), ('info', '提示'), ('warning', '警告'), ('severe', '严重'), ('critical', '紧急')], max_length=20, verbose_name='操作前等级')),
                ('level_after', models.CharField(blank=True, choices=[('safe', '安全'), ('info', '提示'), ('warning', '警告'), ('severe', '严重'), ('critical', '紧急')], max_length=20, verbose_name='操作后等级')),
                ('passage_before', models.CharField(blank=True, choices=[('normal', '正常通行'), ('caution', '谨慎通行'), ('restricted', '限制通行'), ('detour', '建议绕行'), ('closed', '禁止通行')], max_length=30, verbose_name='操作前通行')),
                ('passage_after', models.CharField(blank=True, choices=[('normal', '正常通行'), ('caution', '谨慎通行'), ('restricted', '限制通行'), ('detour', '建议绕行'), ('closed', '禁止通行')], max_length=30, verbose_name='操作后通行')),
                ('description', models.TextField(verbose_name='处置说明')),
                ('disposed_by', models.CharField(max_length=100, verbose_name='处置人员')),
                ('disposed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='处置时间')),
                ('disposal_result', models.TextField(blank=True, verbose_name='处置结果')),
                ('next_step', models.CharField(blank=True, max_length=300, verbose_name='下一步措施')),
                ('is_active', models.BooleanField(default=True, verbose_name='有效记录')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('hazard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposals', to='roads.hazard', verbose_name='关联隐患')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hazard_disposals', to='roads.taskorder', verbose_name='关联工单')),
            ],
            options={
                'verbose_name': '隐患处置记录',
                'verbose_name_plural': '隐患处置记录',
                'ordering': ['-disposed_at'],
            },
        ),
    ]
