# Generated by Django 4.2.11 on 2026-06-20 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0003_hazard_hazard_disposal_road_passage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskorder',
            name='hazard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_orders', to='roads.hazard', verbose_name='关联灾害隐患'),
        ),
        migrations.AlterField(
            model_name='taskorder',
            name='inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_orders', to='roads.inspectionrecord', verbose_name='关联巡查记录'),
        ),
    ]
