# Generated by Django 4.2.11 on 2026-06-20 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0004_taskorder_hazard_alter_taskorder_inspection'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorFlowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(verbose_name='记录日期')),
                ('record_time', models.TimeField(verbose_name='记录时间')),
                ('record_type', models.CharField(choices=[('entry', '进入'), ('exit', '离开'), ('count', '统计')], default='count', max_length=20, verbose_name='记录类型')),
                ('visitor_count', models.IntegerField(verbose_name='游客数量')),
                ('current_occupancy', models.IntegerField(default=0, verbose_name='当前在段人数')),
                ('weather', models.CharField(choices=[('sunny', '晴天'), ('cloudy', '多云'), ('rainy', '雨天'), ('heavy_rain', '暴雨'), ('snowy', '雪天'), ('foggy', '雾天'), ('icy', '冰冻')], default='sunny', max_length=20, verbose_name='天气状况')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('recorded_by', models.CharField(max_length=100, verbose_name='记录人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('road_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_flows', to='roads.roadsection', verbose_name='所属路段')),
            ],
            options={
                'verbose_name': '客流记录',
                'verbose_name_plural': '客流记录',
                'ordering': ['-record_date', '-record_time'],
            },
        ),
        migrations.CreateModel(
            name='TemporaryControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_type', models.CharField(choices=[('full_closure', '全段封闭'), ('partial_closure', '部分封闭'), ('time_restriction', '时段限制'), ('capacity_reduction', '减载限流'), ('single_direction', '单向通行'), ('guided_tour', '跟团游览')], max_length=30, verbose_name='管制类型')),
                ('open_status', models.CharField(choices=[('open', '正常开放'), ('partial', '部分开放'), ('restricted', '限制开放'), ('closed', '暂停开放')], default='restricted', max_length=20, verbose_name='开放状态')),
                ('reason', models.TextField(verbose_name='管制原因')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='预计结束时间')),
                ('adjusted_capacity', models.IntegerField(blank=True, help_text='留空表示按原计划', null=True, verbose_name='调整后承载人数')),
                ('adjusted_open_time', models.TimeField(blank=True, null=True, verbose_name='调整后开放时间')),
                ('adjusted_close_time', models.TimeField(blank=True, null=True, verbose_name='调整后关闭时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否生效中')),
                ('issued_by', models.CharField(max_length=100, verbose_name='发布人')),
                ('notice_public', models.TextField(blank=True, verbose_name='对外公告内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('road_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_controls', to='roads.roadsection', verbose_name='所属路段')),
            ],
            options={
                'verbose_name': '临时管制',
                'verbose_name_plural': '临时管制',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='OpenSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('spring', '春季'), ('summer', '夏季'), ('autumn', '秋季'), ('winter', '冬季')], max_length=20, verbose_name='适用季节')),
                ('weather_condition', models.CharField(choices=[('sunny', '晴天'), ('cloudy', '多云'), ('rainy', '雨天'), ('heavy_rain', '暴雨'), ('snowy', '雪天'), ('foggy', '雾天'), ('icy', '冰冻')], default='sunny', max_length=20, verbose_name='适用天气')),
                ('maintenance_status', models.CharField(choices=[('normal', '正常'), ('maintaining', '养护中'), ('repairing', '修缮中'), ('emergency', '应急抢修')], default='normal', max_length=20, verbose_name='养护状态')),
                ('open_time', models.TimeField(verbose_name='开放开始时间')),
                ('close_time', models.TimeField(verbose_name='开放结束时间')),
                ('max_capacity', models.IntegerField(verbose_name='最大承载人数')),
                ('time_slot_minutes', models.IntegerField(default=60, verbose_name='分时段时长(分钟)')),
                ('slot_max_capacity', models.IntegerField(default=0, help_text='0表示不设分时限流', verbose_name='分时段最大人数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('description', models.TextField(blank=True, verbose_name='备注说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('road_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_schedules', to='roads.roadsection', verbose_name='所属路段')),
            ],
            options={
                'verbose_name': '开放时段计划',
                'verbose_name_plural': '开放时段计划',
                'ordering': ['road_section__code', 'season', '-is_active'],
            },
        ),
    ]
